Objetivo 4
paula1999/Tune-in pull request #16
Opened 2021-11-07 14:58 UTC by paula1999

Se añaden los tests correspondientes y su documentación.

2021-11-07 15:28 UTC, paula1999 commented
Listo para revisión @JJ

2021-11-09 13:08 UTC, JJ requested changes
Estáis siguiendo el flujo de datos del programa, cuando ya os dije en clase que hay que seguir el desarrollo partiendo de las clases más básicas y hacia arriba. Comprueba también que estás testeando la lógica de negocio, y los issues deben ser problemas, no tareas.

2021-11-09 13:08 UTC, JJ commented on README.md
> +Se ha utilizado la herramienta `rspec`.
Haría falta algo más de justificación, porque Ruby seguro que tiene otros tests runners.

2021-11-11 11:45 UTC, paula1999 commented
Listo para revisión @JJ

2021-11-11 19:46 UTC, JJ requested changes
Yo diría que está prácticamente bien, salvo un fichero (o los comentarios en ese fichero) que no están muy justificados.
No se ha implementado gran cosa de la lógica de negocio ni de las clases, así que habrá que avanzar en los siguientes objetivos.

2021-11-11 19:46 UTC, JJ commented on app/lib/daily_song_history.rb
> +    @postal_code = PROVINCES[postal_code-1]
??

2021-11-11 19:46 UTC, JJ commented on app/spec/spec_helper.rb
> +# This file was generated by the `rspec --init` command. Conventionally, all
¿Necesitas todos estos comentarios?

2021-11-11 19:46 UTC, JJ commented on app/spec/spec_helper.rb
> +  config.mock_with :rspec do |mocks|
¿Esto sirve para algo? ¿O está copiado de algún lado?

2021-11-12 11:00 UTC, paula1999 commented on app/lib/daily_song_history.rb
> +    @postal_code = PROVINCES[postal_code-1]
Error mío, ahora lo modifico

2021-11-12 11:03 UTC, paula1999 commented on app/spec/spec_helper.rb
> +  config.mock_with :rspec do |mocks|
Se me generó el archivo al configurar `rspec`, pero estoy viendo ahora que no sirve para nada. También lo modifico

2021-11-12 11:06 UTC, paula1999 commented
Listo para revisión @JJ

2021-11-12 11:17 UTC, JJ approved these changes
:+1:

2021-11-12 11:30 UTC, merged